# Use Ollama base image
FROM ollama/ollama:latest

# Set the working directory
WORKDIR /root

# Copy your gguf model file into the Docker image
# COPY Modelfile /root/
# COPY Phi-3-mini-4k-instruct-q4.gguf /root/.ollama/

EXPOSE 11434
